apiVersion: v1
kind: Namespace
metadata:
  name: nasulog
  labels:
    name: nasulog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticmq
  namespace: nasulog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticmq
  template:
    metadata:
      labels:
        app: elasticmq
    spec:
      containers:
      - name: elasticmq
        image: softwaremill/elasticmq
        ports:
        - containerPort: 9324
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb
  namespace: nasulog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb
  template:
    metadata:
      labels:
        app: dynamodb
    spec:
      containers:
      - name: dynamodb
        image: amazon/dynamodb-local
        ports:
        - containerPort: 9000
        command:
        - "java"
        - "-jar"
        - "DynamoDBLocal.jar"
        - "-sharedDb"
        - "-port"
        - "9000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: nasulog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: nasu/nasulog:v0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: elasticmq
spec:
  type: LoadBalancer
  ports:
  - port: 9324
  selector:
    app: elasticmq
---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb
spec:
  type: LoadBalancer
  ports:
  - port: 9000
  selector:
    app: dynamodb
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: api
